### ISSUE TITLE
Docker Hub image

### ISSUE THREAD

**Issue by fragmuffin** [cqparts/cqparts#125]
Make a docker image for docker-hub so users can run their scripts without a local install (similar to cadquery)

**Release Process**
Docker image should be built post-release to PyPI, this simplifies the image build process, and makes the `cqparts` installation identical on both docker and/or host.

**Ubuntu as basis?**
Probably not, seems a bit bloated.
I want the image to be as small as possible.... possibly the `python3` image as basis.
There were issues using a debian image with FreeCAD, but with python-occ this _may_ not be a problem... I'll just have to try it out and see.

**Tasks**
- [ ] Create docker image for release to Docker Hub
- [ ] Release to Docker Hub as part of release process
- [ ] Document example usage

discussion in: cqparts/cqparts_webapi#3
